services:
  postgres:
    image: postgres:18
    container_name: db-task-manager
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-email-queue
    restart: unless-stopped
    ports:
      - "5672:5672" # conexÃ£o AMQP
      - "15672:15672" # painel web RabbitMQ -> http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASSWORD}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
